name: Build WallCrop

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        python-version: ['3.13']

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install macOS dependencies
      if: matrix.os == 'macos-latest'
      run: |
        brew install python-tk
        
    - name: Install Linux dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev python3-tk

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        python -m pip install -r requirements.txt
        
    - name: Build with PyInstaller
      run: |
        python -m PyInstaller --name WallCrop --windowed --onefile src/wallpaper_cropper.py

    - name: Create release package (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        mkdir WallCrop-Windows
        move dist\WallCrop.exe WallCrop-Windows\
        copy README.md WallCrop-Windows\
        7z a "WallCrop-Windows-${{ github.ref_name }}.zip" WallCrop-Windows\

    - name: Create release package (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        mkdir -p WallCrop-macOS
        cp -r dist/WallCrop WallCrop-macOS/
        cp README.md WallCrop-macOS/
        tar -czf "WallCrop-macOS-${{ github.ref_name }}.tar.gz" WallCrop-macOS/

    - name: Create release package (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        mkdir WallCrop-Linux
        mv dist/WallCrop WallCrop-Linux/
        cp README.md WallCrop-Linux/
        tar -czf "WallCrop-Linux-${{ github.ref_name }}.tar.gz" WallCrop-Linux/

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: WallCrop-${{ matrix.os }}
        path: |
          WallCrop-*-${{ github.ref_name }}.*

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          WallCrop-*-${{ github.ref_name }}.*
        token: ${{ secrets.GITHUB_TOKEN }}